#!/bin/bash

FAFB2DPX_pts="/groups/saalfeld/public/vfb/lm-em-landmarks_v11.csv"
srcjar="/groups/saalfeld/home/bogovicj/dev/bdv/elm-nblast/target/elm-0.0.2-jar-with-dependencies.jar"
java -Xmx2000m -jar "$srcjar" "$FAFB2DPX_pts" "$@" -rm 1.0,1.0,10.0
